version: '3'
services:
    api:
        build: .
        command: nodemon app.js
        ports:
          - "3000:3000"
        volumes:
          - .:/usr/src/app
          - /usr/src/node_modules
        depends_on:
          - mongo
    mongo:
        image: mongo
        ports:
          - "27017:20717"
        volumes:
          - ./data:/data/db